export const animations = [
  {
    id: 'flow-field',
    title: 'Neural Activity',
    description: 'Mouse-reactive neural noise field. Move to warp, click to pulse.',
    path: `${import.meta.env.BASE_URL}animations/flow-field/`,
    tags: ['shader', 'interactive'],
  },
  {
    id: 'face-it-1',
    title: 'Face It 1',
    description: 'Outside me. Drag to rotate, shift+drag to move, scroll to zoom.',
    path: `${import.meta.env.BASE_URL}animations/face-it-1/`,
    tags: ['shader', 'interactive'],
  },
  {
    id: 'wave-horizon',
    title: 'Consciousness 1',
    description: 'A look at my typical brain activity. White peaks are breaking through to the foreground of thought.',
    path: `${import.meta.env.BASE_URL}animations/wave-horizon/`,
    tags: ['3d', 'shader', 'interactive'],
  },
  {
    id: 'wave-horizon-2',
    title: 'Consciousness 2',
    description: 'A look at my typical brain activity. White peaks are breaking through to the foreground of thought.',
    path: `${import.meta.env.BASE_URL}animations/wave-horizon-2/`,
    tags: ['3d', 'shader', 'interactive'],
  },
  {
    id: 'leave-a-message',
    title: 'Leave A Message',
    description: '',
    path: `${import.meta.env.BASE_URL}animations/leave-a-message/`,
    tags: ['3d', 'audio', 'interactive'],
  },
  {
    id: 'connections-1',
    title: 'Connections 1',
    description: 'A 3D grid of 1000 neurons, randomly linking and unlinking as the lattice spins.',
    path: `${import.meta.env.BASE_URL}animations/connections-1/`,
    tags: ['3d', 'interactive'],
  },
  {
    id: 'connections-2',
    title: 'Connections 2',
    description: 'A 3D grid of 1000 neurons, randomly linking and unlinking as the lattice spins.',
    path: `${import.meta.env.BASE_URL}animations/connections-2/`,
    tags: ['3d', 'interactive'],
  },
  {
    id: 'model-loader',
    title: 'Model Loader',
    description: 'Load and inspect GLB, glTF, or OBJ models. Drag to rotate, shift+drag to move, scroll to zoom.',
    path: `${import.meta.env.BASE_URL}animations/model-loader/`,
    tags: ['3d', 'interactive'],
  },
];
